import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Layout } from "@/components/Layout/layout";
const inter = Inter({
  subsets: ["latin"],
  weight: "100"
});
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
export const metadata: Metadata = {
  title: "AGIS Institute",
  description: "Generated by Rahul",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </Layout>
      </body>
    </html>
  );
}
